### ISSUE TITLE
Allow installation on same domain with other apps

### ISSUE THREAD

**Issue by renne** [YunoHost-Apps/technitium-dns_ynh#3]
### Describe the bug

This app package cannot be installed on the same domain with other apps.

### Context

- Hardware: *Proxmox KVM-VM on Intel x86_64*
- YunoHost version: 11.0.9.14 (stable)
- I have access to my server: *SSH | direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 8.1.4~ynh2

### Steps to reproduce

   1. *Try to install the package via Yunohost web-interface*

### Expected behavior

Install package on same domain with other packages/apps.

### Logs
```
Fehlermeldung:

Es tut uns leid, aber diese Applikation erfordert die Installation auf einer eigenen Domain, aber einige andere Applikationen sind bereits auf der Domäne'xxx' installiert. Eine mögliche Lösung ist das Hinzufügen und Verwenden einer Subdomain, die dieser Applikation zugeordnet ist.

```

**Comment by ericgaspar** [comment]
sorry, technitium-dns requires a domain or sub-domain.
