### ISSUE TITLE
Automagically create/update/delete Yunohost domains/records in Technitium

### ISSUE THREAD

**Issue by renne** [YunoHost-Apps/technitium-dns_ynh#4]
### Describe the bug

Please add support to Yunohost to automagically create/update/delete domains/records in Technitium.

### Context

- Hardware: Proxmox KVM on bare metal
- YunoHost version: 11.0.11
- I have access to my server: Through SSH | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 8.1.4~ynh2

### Steps to reproduce

Currently Yunohost can configure DNS ressource records at multiple DNS service providers (e.g. Gandi, OVH, Cloudflare, etc.) via the Lexicon library (called Yunohost autodns).

Yunohost does not create/update/delete domains/records in Technitium.

### Expected behavior

Automagically create/update/delete Yunohost domains/records in Technitium
This will allow to use Technitium as a (hidden) primary nameserver for Yunohost.

**Comment by renne** [comment]
@navanchauhan
@yalh76
Are there any plans for a tighter integration, either directly or via lexicon?

**Comment by yalh76** [comment]
> @navanchauhan @yalh76 Are there any plans for a tighter integration, either directly or via [lexicon](https://github.com/AnalogJ/lexicon/issues/1553)?

no plan, as far as I know

**Comment by navanchauhan** [comment]
This seems like a feature for the core YunoHost project
